# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  eshop:
    image: eshop
    build:
      context: .
      dockerfile: Eshop/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5010:5010
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
